[LOG_FILE]
info_log_path = logs\info.log


[OUTPUT_PATH]
#The directory the district folders are located in. The program will create a folder for each district code in this directory and save the output files in the corresponding district folder. You can change this path if you want to store the output files in a different location.
output_dir = output\districts\

#The name of the excel file that the graphs will be saved to. The program will save the graphs to this file in each district folder. You can change this name if you want to save the graphs to a different file name.
graphs_file_name = graphs.xlsx

[INPUT_PATH]
#The directory the district folders are located in. The program will look for the input files in the corresponding district folder. You can change this path if you want to store the input files in a different location.
input_dir = input\districts

#Name of the input files from USAS. IMPORTANT - the file names below must match the file name in the input directory for the program to work. You can change these names if you want to use different file names, but make sure to update the file names in the input directory as well.
input_file_name = Graphs - Cash Account History.csv
input_exp_pie_file = Graphs - Expenditures Pie Chart.csv
input_rev_pie_file = Graphs - Revenue Pie Chart.csv
formatted_input_file = formatted_file.csv


[USERS]
#This file will contain the email address of the users from each district that the graphs excel file will be sent to.
users_file = users/users.csv


[EMAIL_SETTINGS]
# NOTE - you would need to set up an email account to send the emails from and enter the email address here.
sender_email_address = automation-noreply@example.edu

#Note - this is the email address that will receive error notification and the completion email
admin_email_address = your-email-here@example.org

# NOTE - you would need to set up an email account to send the emails from and enter the email password here. Remove quotes around password
email_sender_password = "" 

# NOTE - you would need to set up an email account to send the emails from and enter the SMTP server address here.
host = smtp.example.com

# NOTE - you would need to set up an email account to send the emails from and enter the SMTP server port here. The default port for SMTP is 587, but it may be different depending on your email provider.
port = 587

# Set to True to enable email sending, False to disable. 
enable_email_sending = FALSE 