[LOG_FILE_PATH]
#This is the path to the log file where the program will write log messages. You can change this path if you want to store the log file in a different location.
log_file = log\info.txt 


[INPUT_FOLDER_PATH]
#This is the path to the parent directory that contains the district folders. Each district folder should contain a user_listings.csv file with the user data for that district. You can change this path if you want to store the input files in a different location.
parent_districts_dir = input\ 


[OUTPUT_FOLDER_PATH]
#This is the path to the output directory where the program will save the output files. You can change this path if you want to store the output files in a different location.
output_folder = output  

 #This is the path to the output file where the program will save the updated user listings with the password expiration status. You can change this path if you want to save the output file in a different location or with a different name.
output_file = output\master_user_listings.csv

[PASSWORD_REMINDER]
# This is the number of days before a password expires that the program will consider the password to be expiring soon. You can change this value to adjust the threshold for when the program will send reminder emails to users with expiring passwords.
password_reminder_threshold = 7 

[EMAIL_SETTINGS]
# NOTE - you would need to set up an email account to send the emails from and enter the email address here.
email_sender_address = automation-noreply@example.edu

#Note - this is the email address that will receive error notification and the completion email
admin_email_address = your-email-here@example.org

# NOTE - you would need to set up an email account to send the emails from and enter the email password here. Remove quotes around password
email_sender_password = "" 

# NOTE - you would need to set up an email account to send the emails from and enter the SMTP server address here.
host = smtp.example.com

# NOTE - you would need to set up an email account to send the emails from and enter the SMTP server port here. The default port for SMTP is 587, but it may be different depending on your email provider.
port = 587

enable_email_sending = False # Set to True to enable email sending, False to disable. 